server:
  port: 9090

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: ${database.url}
    username: ${database.user}
    driver-class-name: org.h2.Driver
    password: ${database.password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  r2dbc:
    url: ${database.urlR2dbc}
  flyway:
    url: ${database.url}
    user: ${database.user}
    password: ${database.password}
    schemas: ${database.schema}
    locations: classpath:db/migration
    enabled: true
  sql:
    init:
      mode: always
      platform: local

database:
  user: sa
  password: "pass"
  url: jdbc:h2:mem:testdb;${database.params}
  urlR2dbc: mem:testdb;SCHEMA=${database.schema};${database.params}
  schema: mutant
  params: DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_LOWER=TRUE
#logging:
#  level:
#    root: debug
